import { auth } from "@/../auth";

export const ROLES = {
  ADMIN: "ADMIN",
  PRESIDENTE: "PRESIDENTE",
  TESOUREIRO: "TESOUREIRO",
  SECRETARIO: "SECRETARIO",
  MEMBRO: "MEMBRO",
} as const;

export type RoleName = (typeof ROLES)[keyof typeof ROLES];

export const PERMISSIONS = {
  MEMBERS_VIEW: "members.view",
  MEMBERS_CREATE: "members.create",
  MEMBERS_UPDATE: "members.update",
  MEMBERS_STATUS: "members.status",
  FEES_VIEW: "fees.view",
  FEES_CREATE: "fees.create",
  FEES_GENERATE: "fees.generate",
  FEES_PAY: "fees.pay",
  FEES_EXEMPT: "fees.exempt",
  FEES_CANCEL: "fees.cancel",
  FINANCE_VIEW: "finance.view",
  FINANCE_CREATE: "finance.create",
  FINANCE_REVERSE: "finance.reverse",
  CASH_OPEN: "cash.open",
  CASH_CLOSE: "cash.close",
  FINANCE_SETTINGS: "finance.settings",
  EVENTS_VIEW: "events.view",
  EVENTS_CREATE: "events.create",
  EVENTS_UPDATE: "events.update",
  EVENTS_PUBLISH: "events.publish",
  EVENTS_CANCEL: "events.cancel",
  EVENTS_TYPES: "events.types",
  REGISTRATIONS_VIEW: "registrations.view",
  REGISTRATIONS_UPDATE: "registrations.update",
  REGISTRATIONS_BENEFITS: "registrations.benefits",
  REGISTRATIONS_PAYMENT: "registrations.payment",
  STOCK_VIEW: "stock.view",
  STOCK_PRODUCTS: "stock.products",
  STOCK_MOVEMENTS: "stock.movements",
  STOCK_ADJUST: "stock.adjust",
  STOCK_SETTINGS: "stock.settings",
  ORDERS_VIEW: "orders.view",
  ORDERS_MANAGE: "orders.manage",
  ORDERS_PAYMENT: "orders.payment",
  ORDERS_CANCEL: "orders.cancel",
  REPORTS_VIEW: "reports.view",
  EVENTS_OPERATION: "events.operation",
  EVENTS_CHECKIN: "events.checkin",
  EVENTS_FINISH: "events.finish",
} as const;

export type PermissionName = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const permissionRoles: Record<PermissionName, RoleName[]> = {
  [PERMISSIONS.MEMBERS_VIEW]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.SECRETARIO],
  [PERMISSIONS.MEMBERS_CREATE]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.SECRETARIO],
  [PERMISSIONS.MEMBERS_UPDATE]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.SECRETARIO],
  [PERMISSIONS.MEMBERS_STATUS]: [ROLES.ADMIN, ROLES.PRESIDENTE],
  [PERMISSIONS.FEES_VIEW]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.TESOUREIRO, ROLES.SECRETARIO],
  [PERMISSIONS.FEES_CREATE]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.TESOUREIRO],
  [PERMISSIONS.FEES_GENERATE]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.TESOUREIRO],
  [PERMISSIONS.FEES_PAY]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.TESOUREIRO],
  [PERMISSIONS.FEES_EXEMPT]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.TESOUREIRO],
  [PERMISSIONS.FEES_CANCEL]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.TESOUREIRO],
  [PERMISSIONS.FINANCE_VIEW]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.TESOUREIRO],
  [PERMISSIONS.FINANCE_CREATE]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.TESOUREIRO],
  [PERMISSIONS.FINANCE_REVERSE]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.TESOUREIRO],
  [PERMISSIONS.CASH_OPEN]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.TESOUREIRO],
  [PERMISSIONS.CASH_CLOSE]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.TESOUREIRO],
  [PERMISSIONS.FINANCE_SETTINGS]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.TESOUREIRO],
  [PERMISSIONS.EVENTS_VIEW]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.SECRETARIO, ROLES.TESOUREIRO],
  [PERMISSIONS.EVENTS_CREATE]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.SECRETARIO],
  [PERMISSIONS.EVENTS_UPDATE]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.SECRETARIO],
  [PERMISSIONS.EVENTS_PUBLISH]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.SECRETARIO],
  [PERMISSIONS.EVENTS_CANCEL]: [ROLES.ADMIN, ROLES.PRESIDENTE],
  [PERMISSIONS.EVENTS_TYPES]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.SECRETARIO],
  [PERMISSIONS.REGISTRATIONS_VIEW]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.SECRETARIO, ROLES.TESOUREIRO],
  [PERMISSIONS.REGISTRATIONS_UPDATE]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.SECRETARIO],
  [PERMISSIONS.REGISTRATIONS_BENEFITS]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.TESOUREIRO],
  [PERMISSIONS.REGISTRATIONS_PAYMENT]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.TESOUREIRO],
  [PERMISSIONS.STOCK_VIEW]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.TESOUREIRO, ROLES.SECRETARIO],
  [PERMISSIONS.STOCK_PRODUCTS]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.TESOUREIRO],
  [PERMISSIONS.STOCK_MOVEMENTS]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.TESOUREIRO],
  [PERMISSIONS.STOCK_ADJUST]: [ROLES.ADMIN, ROLES.PRESIDENTE],
  [PERMISSIONS.STOCK_SETTINGS]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.TESOUREIRO],
  [PERMISSIONS.ORDERS_VIEW]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.TESOUREIRO, ROLES.SECRETARIO],
  [PERMISSIONS.ORDERS_MANAGE]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.TESOUREIRO, ROLES.SECRETARIO],
  [PERMISSIONS.ORDERS_PAYMENT]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.TESOUREIRO],
  [PERMISSIONS.ORDERS_CANCEL]: [ROLES.ADMIN, ROLES.PRESIDENTE],
  [PERMISSIONS.REPORTS_VIEW]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.TESOUREIRO, ROLES.SECRETARIO],
  [PERMISSIONS.EVENTS_OPERATION]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.SECRETARIO, ROLES.TESOUREIRO],
  [PERMISSIONS.EVENTS_CHECKIN]: [ROLES.ADMIN, ROLES.PRESIDENTE, ROLES.SECRETARIO],
  [PERMISSIONS.EVENTS_FINISH]: [ROLES.ADMIN, ROLES.PRESIDENTE],
};

export async function getCurrentSession() {
  return auth();
}

export async function requireRole(allowedRoles: RoleName[]) {
  const session = await auth();
  const roles = session?.user?.roles ?? [];

  if (!session?.user) throw new Error("UNAUTHENTICATED");
  if (!roles.some((role) => allowedRoles.includes(role as RoleName))) {
    throw new Error("FORBIDDEN");
  }

  return session;
}

export async function requirePermission(permission: PermissionName) {
  return requireRole(permissionRoles[permission]);
}

export function hasRole(roles: string[] | undefined, allowedRoles: RoleName[]) {
  return (roles ?? []).some((role) => allowedRoles.includes(role as RoleName));
}

export function hasPermission(roles: string[] | undefined, permission: PermissionName) {
  return hasRole(roles, permissionRoles[permission]);
}
