import { prisma } from "@/lib/prisma";
import { PERMISSIONS, requirePermission } from "@/lib/auth/permissions";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { createCashCategory, createPaymentMethod, toggleCashCategory, togglePaymentMethod } from "../actions";

export default async function FinanceSettingsPage({searchParams}:{searchParams:Promise<{category?:string;method?:string;error?:string}>}){
 await requirePermission(PERMISSIONS.FINANCE_SETTINGS); const q=await searchParams; const [categories,methods]=await Promise.all([prisma.cashCategory.findMany({orderBy:[{type:"asc"},{name:"asc"}]}),prisma.paymentMethod.findMany({orderBy:{name:"asc"}})]);
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Configurações financeiras</h1><p className="text-muted-foreground">Categorias e formas de pagamento.</p></div>{(q.category||q.method)&&<div className="rounded-md border p-3 text-sm">Configuração salva.</div>}{q.error&&<div className="rounded-md border p-3 text-sm">Não foi possível concluir: {q.error}.</div>}<div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle>Categorias</CardTitle><CardDescription>Classificam receitas e despesas.</CardDescription></CardHeader><CardContent className="space-y-5"><form action={createCashCategory} className="grid gap-3 sm:grid-cols-2"><input name="name" className="input" placeholder="Nome" required/><select name="type" className="input"><option value="INCOME">Receita</option><option value="EXPENSE">Despesa</option></select><input name="description" className="input sm:col-span-2" placeholder="Descrição"/><div className="sm:col-span-2"><Button type="submit">Adicionar categoria</Button></div></form><div className="space-y-2">{categories.map(c=><div key={c.id} className="flex items-center justify-between rounded-md border p-3"><div><div className="font-medium">{c.name}</div><div className="text-xs text-muted-foreground">{c.type==="INCOME"?"Receita":"Despesa"}</div></div><form action={toggleCashCategory.bind(null,c.id)}><Button size="sm" variant="outline">{c.active?"Desativar":"Ativar"}</Button></form></div>)}</div></CardContent></Card><Card><CardHeader><CardTitle>Formas de pagamento</CardTitle><CardDescription>Usadas em mensalidades, eventos, comandas e lançamentos.</CardDescription></CardHeader><CardContent className="space-y-5"><form action={createPaymentMethod} className="grid gap-3 sm:grid-cols-2"><input name="name" className="input" placeholder="Nome" required/><select name="type" className="input"><option value="CASH">Dinheiro</option><option value="PIX">PIX</option><option value="DEBIT_CARD">Débito</option><option value="CREDIT_CARD">Crédito</option><option value="BANK_TRANSFER">Transferência</option><option value="OTHER">Outro</option></select><div className="sm:col-span-2"><Button type="submit">Adicionar forma</Button></div></form><div className="space-y-2">{methods.map(m=><div key={m.id} className="flex items-center justify-between rounded-md border p-3"><div className="flex items-center gap-2"><span className="font-medium">{m.name}</span><Badge>{m.type}</Badge></div><form action={togglePaymentMethod.bind(null,m.id)}><Button size="sm" variant="outline">{m.active?"Desativar":"Ativar"}</Button></form></div>)}</div></CardContent></Card></div></div>
}
