import { notFound } from "next/navigation";
import { OrderStatus } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { PERMISSIONS,hasPermission,requirePermission } from "@/lib/auth/permissions";
import { stockBalances } from "@/lib/stock/balance";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { SubmitButton } from "@/components/ui/submit-button";
import { AdminOrderItemForm } from "@/components/orders/admin-order-item-form";
import { cancelOrder,cancelOrderItem,closeOrder,confirmOrderPayment,reopenOrder } from "../actions";
import { ORDER_STATUS_LABELS,formatOrderMoney } from "@/lib/orders/utils";
export default async function OrderDetail({params}:{params:Promise<{id:string}>}){const session=await requirePermission(PERMISSIONS.ORDERS_VIEW);const {id}=await params;const order=await prisma.order.findUnique({where:{id},include:{event:true,items:{orderBy:{createdAt:"asc"}},cashTransactions:{include:{category:true,createdBy:{select:{name:true}}},orderBy:{createdAt:"desc"}}}});if(!order)notFound();const dbProducts=order.status===OrderStatus.OPEN?await prisma.product.findMany({where:{active:true},orderBy:{name:"asc"},select:{id:true,name:true,salePrice:true,unit:true}}):[];const balances=await stockBalances(dbProducts.map(p=>p.id));const products=dbProducts.map(p=>({...p,stock:balances.get(p.id)??0}));return <div className="space-y-6"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><h1 className="text-2xl font-bold">Comanda de {order.customerName}</h1><p className="text-muted-foreground">{order.event?.name??"Reunião / consumo avulso"} · {order.customerPhone||"Sem telefone"}</p></div><div className="flex items-center gap-3"><Badge>{ORDER_STATUS_LABELS[order.status]}</Badge>{order.status===OrderStatus.PAID&&<a href={`/api/recibos/comanda/${order.id}`} target="_blank" className="text-sm font-medium underline">Recibo PDF</a>}</div></div>
<Card><CardHeader><CardTitle>Consumos</CardTitle></CardHeader><CardContent className="space-y-4">{order.status===OrderStatus.OPEN&&hasPermission(session.user.roles,PERMISSIONS.ORDERS_MANAGE)&&<AdminOrderItemForm orderId={order.id} products={products.map(p=>({id:p.id,name:p.name,salePrice:p.salePrice.toString(),stock:p.stock,unit:p.unit}))}/>}<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-y text-left"><tr><th className="p-3">Produto</th><th className="p-3">Qtd.</th><th className="p-3">Unitário</th><th className="p-3">Total</th><th></th></tr></thead><tbody>{order.items.map(i=><tr key={i.id} className={i.status==="CANCELED"?"border-b opacity-50":"border-b"}><td className="p-3">{i.productName}{i.status==="CANCELED"&&<span className="ml-2 text-xs">(cancelado)</span>}</td><td className="p-3">{Number(i.quantity).toLocaleString("pt-BR",{maximumFractionDigits:3})}</td><td className="p-3">{formatOrderMoney(i.unitPrice)}</td><td className="p-3 font-medium">{formatOrderMoney(i.totalPrice)}</td><td className="p-3 text-right">{order.status===OrderStatus.OPEN&&i.status==="ACTIVE"&&hasPermission(session.user.roles,PERMISSIONS.ORDERS_MANAGE)&&<form action={cancelOrderItem.bind(null,i.id)}><SubmitButton size="sm" variant="outline" pendingText="Removendo...">Remover</SubmitButton></form>}</td></tr>)}{!order.items.length&&<tr><td colSpan={5} className="p-8 text-center text-muted-foreground">Sem itens.</td></tr>}</tbody></table></div><div className="flex justify-end border-t pt-4"><div className="text-right"><div className="text-sm text-muted-foreground">Total</div><div className="text-2xl font-bold">{formatOrderMoney(order.totalAmount)}</div></div></div></CardContent></Card>
<div className="flex flex-wrap gap-2">{order.status===OrderStatus.OPEN&&hasPermission(session.user.roles,PERMISSIONS.ORDERS_MANAGE)&&<form action={closeOrder.bind(null,order.id)}><SubmitButton pendingText="Fechando...">Fechar para pagamento</SubmitButton></form>}{order.status===OrderStatus.AWAITING_PAYMENT&&hasPermission(session.user.roles,PERMISSIONS.ORDERS_PAYMENT)&&<form action={confirmOrderPayment.bind(null,order.id)}><SubmitButton pendingText="Confirmando...">Confirmar PIX recebido</SubmitButton></form>}{order.status===OrderStatus.AWAITING_PAYMENT&&hasPermission(session.user.roles,PERMISSIONS.ORDERS_MANAGE)&&<form action={reopenOrder.bind(null,order.id)}><SubmitButton variant="outline" pendingText="Reabrindo...">Reabrir</SubmitButton></form>}{![OrderStatus.PAID,OrderStatus.CANCELED].includes(order.status)&&hasPermission(session.user.roles,PERMISSIONS.ORDERS_CANCEL)&&<form action={cancelOrder.bind(null,order.id)}><SubmitButton variant="outline" pendingText="Cancelando...">Cancelar comanda</SubmitButton></form>}<a href={`/comanda/${order.publicToken}`} target="_blank" rel="noreferrer"><Button variant="secondary">Abrir visão pública</Button></a></div>
{order.status===OrderStatus.AWAITING_PAYMENT&&<Card><CardHeader><CardTitle>Pagamento</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">O cliente visualiza o QR Code e a chave PIX na página pública. A confirmação é manual pelo botão acima.</CardContent></Card>}
{order.cashTransactions.length>0&&<Card><CardHeader><CardTitle>Financeiro</CardTitle></CardHeader><CardContent>{order.cashTransactions.map(t=><div key={t.id} className="flex justify-between border-b py-2 text-sm"><span>{t.description}</span><strong>{formatOrderMoney(t.amount)}</strong></div>)}</CardContent></Card>}</div>}
