import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { PERMISSIONS, hasPermission, requirePermission } from "@/lib/auth/permissions";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { formatMoney } from "@/lib/finance/utils";
import { closeCashRegister, openCashRegister } from "../actions";

export default async function CashPage({searchParams}:{searchParams:Promise<{opened?:string;closed?:string;error?:string}>}){
 const session=await requirePermission(PERMISSIONS.FINANCE_VIEW); const q=await searchParams;
 const [openCash,history]=await Promise.all([prisma.cashRegister.findFirst({where:{status:"OPEN"},include:{openedBy:{select:{name:true}},transactions:{where:{reversedAt:null}}},orderBy:{openedAt:"desc"}}),prisma.cashRegister.findMany({where:{status:"CLOSED"},include:{openedBy:{select:{name:true}},closedBy:{select:{name:true}}},orderBy:{closedAt:"desc"},take:20})]);
 let currentExpected=openCash?Number(openCash.openingBalance):0; if(openCash)for(const t of openCash.transactions){if(t.type==="INCOME")currentExpected+=Number(t.amount); else if(t.type==="EXPENSE")currentExpected-=Number(t.amount); else if(t.type==="REVERSAL"){const m=t.metadata as {originalType?:string}|null; currentExpected+=m?.originalType==="EXPENSE"?Number(t.amount):-Number(t.amount)}}
 return <div className="space-y-6"><div><Link href="/admin/financeiro" className="text-sm text-muted-foreground hover:underline">← Financeiro</Link><h1 className="mt-2 text-2xl font-bold">Caixa</h1><p className="text-muted-foreground">Abertura, conferência e fechamento diário.</p></div>{q.opened&&<div className="rounded-md border p-3 text-sm">Caixa aberto.</div>}{q.closed&&<div className="rounded-md border p-3 text-sm">Caixa fechado.</div>}{q.error&&<div className="rounded-md border p-3 text-sm">Não foi possível concluir: {q.error}.</div>}{openCash?<div className="grid gap-4 lg:grid-cols-3"><Card><CardHeader><CardTitle>Caixa atual</CardTitle><CardDescription>Aberto por {openCash.openedBy.name}</CardDescription></CardHeader><CardContent><div className="text-3xl font-bold">{formatMoney(currentExpected)}</div><p className="mt-1 text-sm text-muted-foreground">Saldo esperado neste momento</p><div className="mt-4 text-sm">Saldo inicial: {formatMoney(openCash.openingBalance.toString())}<br/>Aberto em: {new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(openCash.openedAt)}</div></CardContent></Card><Card className="lg:col-span-2"><CardHeader><CardTitle>Fechar caixa</CardTitle><CardDescription>Informe o valor contado fisicamente. A diferença será registrada.</CardDescription></CardHeader><CardContent>{hasPermission(session.user.roles,PERMISSIONS.CASH_CLOSE)?<form action={closeCashRegister.bind(null,openCash.id)} className="grid gap-4 sm:grid-cols-2"><label className="space-y-1 text-sm"><span className="font-medium">Saldo contado</span><input name="closingBalance" type="number" min="0" step="0.01" className="input" required/></label><label className="space-y-1 text-sm sm:col-span-2"><span className="font-medium">Observações</span><textarea name="notes" className="min-h-24 w-full rounded-md border bg-background p-3 text-sm"/></label><div className="sm:col-span-2"><Button type="submit">Fechar caixa</Button></div></form>:<p className="text-sm text-muted-foreground">Você não possui permissão para fechar o caixa.</p>}</CardContent></Card></div>:<Card><CardHeader><CardTitle>Abrir novo caixa</CardTitle><CardDescription>Somente um caixa pode permanecer aberto por vez.</CardDescription></CardHeader><CardContent>{hasPermission(session.user.roles,PERMISSIONS.CASH_OPEN)?<form action={openCashRegister} className="grid gap-4 sm:grid-cols-2"><label className="space-y-1 text-sm"><span className="font-medium">Saldo inicial</span><input name="openingBalance" type="number" min="0" step="0.01" defaultValue="0.00" className="input" required/></label><label className="space-y-1 text-sm sm:col-span-2"><span className="font-medium">Observações</span><textarea name="notes" className="min-h-24 w-full rounded-md border bg-background p-3 text-sm"/></label><div className="sm:col-span-2"><Button type="submit">Abrir caixa</Button></div></form>:<p className="text-sm text-muted-foreground">Você não possui permissão para abrir o caixa.</p>}</CardContent></Card>}
 <Card><CardHeader><CardTitle>Últimos fechamentos</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-y bg-muted/50 text-left"><tr><th className="px-3 py-2">Abertura</th><th className="px-3 py-2">Fechamento</th><th className="px-3 py-2">Esperado</th><th className="px-3 py-2">Contado</th><th className="px-3 py-2">Diferença</th></tr></thead><tbody>{history.map(c=><tr key={c.id} className="border-b"><td className="px-3 py-2">{new Intl.DateTimeFormat("pt-BR").format(c.openedAt)}</td><td className="px-3 py-2">{c.closedAt?new Intl.DateTimeFormat("pt-BR").format(c.closedAt):"—"}</td><td className="px-3 py-2">{c.expectedBalance?formatMoney(c.expectedBalance.toString()):"—"}</td><td className="px-3 py-2">{c.closingBalance?formatMoney(c.closingBalance.toString()):"—"}</td><td className="px-3 py-2">{c.difference?formatMoney(c.difference.toString()):"—"}</td></tr>)}{!history.length&&<tr><td colSpan={5} className="px-3 py-8 text-center text-muted-foreground">Nenhum caixa fechado.</td></tr>}</tbody></table></div></CardContent></Card></div>
}
