import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { PERMISSIONS, requirePermission } from "@/lib/auth/permissions";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { createTransaction } from "../actions";

export default async function NewTransactionPage({searchParams}:{searchParams:Promise<{error?:string}>}){
  await requirePermission(PERMISSIONS.FINANCE_CREATE); const params=await searchParams;
  const [categories,methods,events]=await Promise.all([prisma.cashCategory.findMany({where:{active:true},orderBy:{name:"asc"}}),prisma.paymentMethod.findMany({where:{active:true},orderBy:{name:"asc"}}),prisma.event.findMany({orderBy:{startsAt:"desc"},take:100,select:{id:true,name:true}})]);
  const now=new Date(); const local=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,16);
  return <div className="mx-auto max-w-3xl space-y-6"><div><Link href="/admin/financeiro" className="text-sm text-muted-foreground hover:underline">← Voltar</Link><h1 className="mt-2 text-2xl font-bold">Novo lançamento</h1></div>{params.error&&<div className="rounded-md border p-3 text-sm">Dados inválidos.</div>}<Card><CardHeader><CardTitle>Movimentação financeira</CardTitle><CardDescription>Entradas e saídas manuais. Movimentações automáticas de mensalidades continuam vinculadas ao módulo de origem.</CardDescription></CardHeader><CardContent><form action={createTransaction} className="grid gap-4 sm:grid-cols-2"><Field label="Tipo"><select name="type" className="input" required><option value="INCOME">Receita</option><option value="EXPENSE">Despesa</option></select></Field><Field label="Valor"><input name="amount" type="number" min="0.01" step="0.01" className="input" required/></Field><Field label="Categoria"><select name="categoryId" className="input" required><option value="">Selecione</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name} — {c.type==="INCOME"?"Receita":"Despesa"}</option>)}</select></Field><Field label="Forma de pagamento"><select name="paymentMethodId" className="input"><option value="">Não informado</option>{methods.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><Field label="Data/hora"><input name="occurredAt" type="datetime-local" defaultValue={local} className="input" required/></Field><Field label="Evento (opcional)"><select name="eventId" className="input"><option value="">Sem evento</option>{events.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></Field><label className="space-y-1 text-sm sm:col-span-2"><span className="font-medium">Descrição</span><input name="description" className="input" required maxLength={240}/></label><label className="space-y-1 text-sm sm:col-span-2"><span className="font-medium">URL do comprovante (opcional)</span><input name="attachmentUrl" type="url" className="input" placeholder="https://..."/></label><div className="sm:col-span-2"><Button type="submit">Salvar lançamento</Button></div></form></CardContent></Card></div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="space-y-1 text-sm"><span className="font-medium">{label}</span>{children}</label>}
