import { ExportButtons } from "@/components/admin/export-buttons";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { PERMISSIONS, requirePermission } from "@/lib/auth/permissions";
import { getFeesReport } from "@/lib/reports/data";
import { money, percentage } from "@/lib/reports/utils";

export default async function FeesReportPage({searchParams}:{searchParams:Promise<{year?:string;month?:string}>}){
  await requirePermission(PERMISSIONS.REPORTS_VIEW); const p=await searchParams; const report=await getFeesReport(Number(p.year),Number(p.month));
  const exportUrl=`/api/export/mensalidades?year=${report.year}&month=${report.month}`; const issued=report.paid.count+report.pending.count+report.exempt.count; const paidRate=percentage(report.paid.count,report.paid.count+report.pending.count);
  return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-bold tracking-tight">Relatório de mensalidades</h1><p className="text-muted-foreground">Arrecadação e inadimplência por competência.</p></div><ExportButtons baseUrl={exportUrl}/></div>
  <form className="grid gap-3 rounded-xl border bg-card p-4 sm:grid-cols-[140px_160px_auto]"><input className="input" type="number" name="year" min="2000" max="2100" defaultValue={report.year}/><select className="input" name="month" defaultValue={report.month}>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{new Intl.DateTimeFormat("pt-BR",{month:"long"}).format(new Date(2026,i,1))}</option>)}</select><Button type="submit">Aplicar competência</Button></form>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat title="Recebido" value={money(report.paid.amount)} note={`${report.paid.count} mensalidade(s)`}/><Stat title="Pendente" value={money(report.pending.amount)} note={`${report.pending.count} mensalidade(s)`}/><Stat title="Taxa de pagamento" value={`${paidRate}%`} note={`${issued} lançamento(s) na competência`}/><Stat title="Isentos" value={String(report.exempt.count)} note="mensalidades isentas"/></div>
  <Card><CardHeader><CardTitle>Inadimplentes</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-y bg-muted/50 text-left"><tr><th className="px-3 py-2">Membro</th><th className="px-3 py-2">Competência</th><th className="px-3 py-2">Vencimento</th><th className="px-3 py-2 text-right">Valor</th><th></th></tr></thead><tbody>{report.overdue.map(f=><tr key={f.id} className="border-b"><td className="px-3 py-2"><div className="font-medium">{f.member}</div><div className="text-xs text-muted-foreground">{f.phone??""}</div></td><td className="px-3 py-2">{String(f.month).padStart(2,"0")}/{f.year}</td><td className="px-3 py-2">{f.dueDate?new Intl.DateTimeFormat("pt-BR").format(f.dueDate):"—"}</td><td className="px-3 py-2 text-right">{money(f.amount)}</td><td className="px-3 py-2 text-right"><Link className="font-medium hover:underline" href={`/admin/mensalidades/${f.id}`}>Abrir</Link></td></tr>)}{!report.overdue.length&&<tr><td colSpan={5} className="px-3 py-8 text-center text-muted-foreground">Nenhuma mensalidade vencida.</td></tr>}</tbody></table></div></CardContent></Card></div>
}
function Stat({title,value,note}:{title:string;value:string;note:string}){return <Card><CardHeader className="pb-2"><CardTitle className="text-sm">{title}</CardTitle></CardHeader><CardContent><div className="text-2xl font-bold">{value}</div><p className="mt-1 text-xs text-muted-foreground">{note}</p></CardContent></Card>}
