import Link from "next/link";
import { Prisma } from "@prisma/client";
import { AlertTriangle, ArrowDownToLine, ArrowUpFromLine, Boxes, Plus, Search, Settings } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { PERMISSIONS, hasPermission, requirePermission } from "@/lib/auth/permissions";
import { Button } from "@/components/ui/button"; import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card"; import { Badge } from "@/components/ui/badge";
import { signedQuantity, formatQuantity } from "@/lib/stock/utils"; import { stockBalances } from "@/lib/stock/balance"; import { formatMoney } from "@/lib/finance/utils";
export default async function StockPage({searchParams}:{searchParams:Promise<{q?:string;category?:string;status?:string;page?:string}>}){
 const session=await requirePermission(PERMISSIONS.STOCK_VIEW); const sp=await searchParams; const q=sp.q?.trim()??""; const page=Math.max(Number(sp.page)||1,1),take=25;
 const where:Prisma.ProductWhereInput={...(q?{OR:[{name:{contains:q}},{sku:{contains:q}}]}:{}),...(sp.category?{categoryId:sp.category}:{}),...(sp.status==="active"?{active:true}:sp.status==="inactive"?{active:false}:{})};
 const [products,total,categories,recent]=await Promise.all([prisma.product.findMany({where,include:{category:true},orderBy:{name:"asc"},skip:(page-1)*take,take}),prisma.product.count({where}),prisma.productCategory.findMany({where:{active:true},orderBy:{name:"asc"}}),prisma.stockMovement.findMany({take:12,orderBy:{createdAt:"desc"},include:{product:true,event:{select:{name:true}},createdBy:{select:{name:true}},reversalOf:{select:{id:true}}}})]);
 const balances=await stockBalances(products.map(p=>p.id)); const low=products.filter(p=>(balances.get(p.id)??0)<=Number(p.minimumStock)); const pages=Math.max(Math.ceil(total/take),1);
 return <div className="space-y-6"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><h1 className="text-2xl font-bold tracking-tight">Estoque</h1><p className="text-muted-foreground">Saldo calculado pelo histórico de movimentações.</p></div><div className="flex flex-wrap gap-2">{hasPermission(session.user.roles,PERMISSIONS.STOCK_MOVEMENTS)&&<Link href="/admin/estoque/movimentacoes/nova"><Button><ArrowDownToLine className="mr-2 h-4 w-4"/>Movimentar</Button></Link>}{hasPermission(session.user.roles,PERMISSIONS.STOCK_PRODUCTS)&&<Link href="/admin/estoque/produtos/novo"><Button variant="secondary"><Plus className="mr-2 h-4 w-4"/>Produto</Button></Link>}{hasPermission(session.user.roles,PERMISSIONS.STOCK_SETTINGS)&&<Link href="/admin/estoque/categorias"><Button variant="outline"><Settings className="mr-2 h-4 w-4"/>Categorias</Button></Link>}</div></div>
 <div className="grid gap-4 md:grid-cols-3"><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Produtos</CardTitle></CardHeader><CardContent><div className="text-2xl font-bold">{total}</div></CardContent></Card><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Abaixo do mínimo nesta página</CardTitle></CardHeader><CardContent><div className="flex items-center gap-2 text-2xl font-bold"><AlertTriangle className="h-5 w-5"/>{low.length}</div></CardContent></Card><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Movimentações recentes</CardTitle></CardHeader><CardContent><div className="text-2xl font-bold">{recent.length}</div></CardContent></Card></div>
 <Card><CardContent className="pt-6"><form className="mb-5 grid gap-3 md:grid-cols-[1fr_220px_160px_auto]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><input name="q" defaultValue={q} className="input pl-9" placeholder="Produto ou SKU"/></div><select name="category" defaultValue={sp.category??""} className="input"><option value="">Todas categorias</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select name="status" defaultValue={sp.status??""} className="input"><option value="">Todos</option><option value="active">Ativos</option><option value="inactive">Inativos</option></select><Button type="submit" variant="secondary">Filtrar</Button></form><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-y bg-muted/50 text-left"><tr><th className="px-4 py-3">Produto</th><th className="px-4 py-3">Categoria</th><th className="px-4 py-3">Saldo</th><th className="px-4 py-3">Mínimo</th><th className="px-4 py-3">Venda</th><th></th></tr></thead><tbody>{products.map(p=>{const b=balances.get(p.id)??0;return <tr key={p.id} className="border-b"><td className="px-4 py-3"><div className="font-medium">{p.name}</div><div className="text-xs text-muted-foreground">{p.sku||"Sem SKU"} · {p.active?"Ativo":"Inativo"}</div></td><td className="px-4 py-3">{p.category?.name??"—"}</td><td className="px-4 py-3"><span className="font-semibold">{formatQuantity(b,p.unit)}</span>{b<=Number(p.minimumStock)&&<Badge className="ml-2">Baixo</Badge>}</td><td className="px-4 py-3">{formatQuantity(p.minimumStock.toString(),p.unit)}</td><td className="px-4 py-3">{formatMoney(p.salePrice.toString())}</td><td className="px-4 py-3 text-right"><Link className="font-medium hover:underline" href={`/admin/estoque/produtos/${p.id}`}>Abrir</Link></td></tr>})}{!products.length&&<tr><td colSpan={6} className="px-4 py-10 text-center text-muted-foreground">Nenhum produto encontrado.</td></tr>}</tbody></table></div><div className="mt-4 flex justify-between text-sm"><span>Página {page} de {pages}</span><div className="flex gap-2">{page>1&&<Link href={`?page=${page-1}`}><Button size="sm" variant="outline">Anterior</Button></Link>}{page<pages&&<Link href={`?page=${page+1}`}><Button size="sm" variant="outline">Próxima</Button></Link>}</div></div></CardContent></Card>
 <Card><CardHeader><CardTitle>Últimas movimentações</CardTitle></CardHeader><CardContent><div className="space-y-3">{recent.map(m=><div key={m.id} className="flex items-center justify-between gap-4 border-b pb-3 text-sm"><div><div className="font-medium">{m.product.name}</div><div className="text-xs text-muted-foreground">{m.event?.name??"Sem evento"} · {m.createdBy?.name??"Sistema"}{m.reversalOf&&" · Estorno"}</div></div><div className="text-right"><div className="font-semibold">{signedQuantity(m.type,m.quantity)>0?"+":""}{formatQuantity(signedQuantity(m.type,m.quantity),m.product.unit)}</div><div className="text-xs text-muted-foreground">{new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(m.createdAt)}</div></div></div>)}</div></CardContent></Card></div>
}
